# Site settings
title: GeekArtT Tech Blog
email: 
description: "GeekArtT Tech Blog"
baseurl: ""
url: "http://kid551.github.io"
github_username:  kid551

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
